apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    spec:
      #nodeName: xxx # 可指定节点
      #hostNetwork: true # 同宿主机网络
      restartPolicy: OnFailure
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "sleep 3600"
